name: workflows events

on:
  push:
    branches:
      - main

jobs:
  events_learning:
    runs-on: ubuntu-latest
    steps:
      - name: push event
        run: |
          npm -v
          node -v
