name: workflows events

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]
jobs:
  events_learning:
    runs-on: ubuntu-latest
    steps:
      - name: push event
        run: |
          npm -v
          node -v
